<a href="https://colab.research.google.com/github/saiavinash77/google_automation_bot/blob/main/Revise_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
from time import process_time

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0005306410000001094


In [ ]:
python_list = [i for i in range(1,1000)]

start_time = process_time()

add_values = [i for i in python_list]

end_time = process_time()

print(end_time - start_time)

7.789900000076955e-05


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
a= np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
b= np.array([[5,6,7,8,9],[4,5,6,7,8]])
print(b)
type(b)

[[5 6 7 8 9]
 [4 5 6 7 8]]


numpy.ndarray

In [ ]:
b.shape

(2, 5)

In [ ]:
x= np.zeros((4,5),dtype=float)
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr2 = np.ones((4,6))
arr2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
arr5 = np.ones((3,4))
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
z=np.full((4,5),5)
z

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

creating an identity matrix

In [ ]:
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

random


In [ ]:
b = np.random.random((3,4))
b

array([[0.44584791, 0.00902254, 0.33008009, 0.49461723],
       [0.3736922 , 0.86518494, 0.02816131, 0.52947106],
       [0.13263193, 0.80844745, 0.76141249, 0.55347049]])

In [ ]:
c=np.random.randint((3,4))
c

array([0, 1])

Create a numpy array with random values

In [ ]:
d = np.random.randint(10,100,(3,5))
d

array([[28, 21, 89, 33, 75],
       [30, 50, 34, 75, 72],
       [52, 75, 34, 17, 82]])

In [ ]:
arrR = np.random.randint(1,101,(5,3))

In [ ]:
arrR

array([[43, 28, 76],
       [62, 86, 18],
       [14, 35, 50],
       [78,  5, 66],
       [86, 29, 71]])

In [ ]:
arr

In [ ]:
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
e = np.arange(10,30,5)
e

array([10, 15, 20, 25])

In [ ]:
a = np.arange(1,101,5)

In [ ]:

a

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [ ]:
list2 = [10,20,30,40]
np_array = np.array(list2)
print(np_array)
type(np_array)

[10 20 30 40]


numpy.ndarray

In [ ]:
list5 = [11,22,33,44,55]
numpy_arr = np.array(list5)
print(numpy_arr)
type(numpy_arr)

[11 22 33 44 55]


numpy.ndarray

In [ ]:
cd = np.random.randint(1,101,(5,5))
cd

array([[87, 34, 70, 24, 69],
       [14, 37, 77, 16, 97],
       [57, 51, 10, 28, 71],
       [41, 62, 99, 62, 17],
       [46, 56, 63, 87, 54]])

In [ ]:
print(cd.shape)

(5, 5)


In [ ]:
print(cd.ndim)

2


In [ ]:
print(cd.size)

2


In [ ]:
print(cd.dtype)

int64


Mathematical Operations on an np array()

In [ ]:
List1 = [1,2,3,4,5]
List2 = [6,7,8,9,10]
print(List1 + List2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))

In [ ]:
a

array([[8, 8, 9],
       [5, 2, 9],
       [8, 9, 9]])

In [ ]:
b = np.random.randint(10,20,(3,3))
b

array([[12, 11, 15],
       [10, 18, 14],
       [10, 15, 19]])

In [ ]:
print(b)

[[12 11 15]
 [10 18 14]
 [10 15 19]]


In [ ]:
print(a+b)


[[20 19 24]
 [15 20 23]
 [18 24 28]]


In [ ]:
print(a-b)

[[ -4  -3  -6]
 [ -5 -16  -5]
 [ -2  -6 -10]]


In [ ]:
print(a*b)

[[ 96  88 135]
 [ 50  36 126]
 [ 80 135 171]]


In [ ]:
print(a/b)

[[0.66666667 0.72727273 0.6       ]
 [0.5        0.11111111 0.64285714]
 [0.8        0.6        0.47368421]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
array

array([[1, 1, 9],
       [0, 9, 7]])

In [ ]:
arr = np.random.randint(0,10,(3,2))
arr
# arr.shape

array([[1, 6],
       [3, 0],
       [2, 4]])

In [ ]:
arr.size

6

In [ ]:
transpose = np.transpose(arr)
transpose

array([[1, 3, 2],
       [6, 0, 4]])

In [ ]:
trans2 = transpose.T
print(trans2)

[[1 6]
 [3 0]
 [2 4]]


In [ ]:
# reshapingg an array
a = np.random.randint(0,10,(2,3))
a
# a.shape

array([[4, 1, 1],
       [3, 2, 2]])

In [ ]:
b = a.reshape(3,2)
print(b)

[[4 1]
 [1 3]
 [2 2]]
